name: Test React app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - name: Setup Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Install dependencies
        run: yarn
      
      - name: Run tests
        run: yarn run test
      
      - name: Create production build
        run: yarn run build